### ISSUE TITLE
Batch

### ISSUE THREAD

**Issue by rtoshiro** [winterDroid/android-drawable-importer-intellij-plugin#128]
When I try to use Batch Drawable Importer and select more than one file at once, it threw an exception:
```
Unable to create directory /drawable-xxhdpi
java.io.IOException: Unable to create directory /drawable-xxhdpi
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2384)
	at de.mprengemann.intellij.plugin.androidicons.images.RefactoringTask.copy(RefactoringTask.java:180)
	at de.mprengemann.intellij.plugin.androidicons.images.RefactoringTask.move(RefactoringTask.java:227)
	at de.mprengemann.intellij.plugin.androidicons.images.RefactoringTask.access$200(RefactoringTask.java:45)
	at de.mprengemann.intellij.plugin.androidicons.images.RefactoringTask$1.run(RefactoringTask.java:75)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by winterDroid** [comment]
@rtoshiro mmh I just tried the Batch Drawable Importer and it is just working fine for me. Can you provide some more examples? Did you specify all required information? It looks a bit like that you did not select a target resource root. Is that possible?

**Comment by rtoshiro** [comment]
Hi @winterDroid 
Sorry, you are right. The resource target was empty. 
I thought I was filled because when I select only one file, It recognizes the target directory automatically. Are there any way to recognize the directory automatically like when we select only one file?
Thank you.

**Comment by winterDroid** [comment]
No worries. It should be filled automatically in the same way.. I'll recheck what can cause that it is not filled.

**Comment by Flimm** [comment]
I had exactly the same problem, getting the error `Unable to create directory /drawable-mdpi`.

Simply filling in the "resource target" column of the Android Drawable Importer dialogue fixed it. I think the dialogue shouldn't let you run if it hasn't been filled in.
