### ISSUE TITLE
Android Studio 3.6 Canary 12

### ISSUE THREAD

**Issue by kikasik** [winterDroid/android-drawable-importer-intellij-plugin#165]
Please fix! Version 0.5-81
This error appears when I do **Batch Drawable Import**:

java.lang.NoSuchMethodError: org.jetbrains.android.facet.AndroidFacet.getAllResourceDirectories()Ljava/util/List;
	at de.mprengemann.intellij.plugin.androidicons.util.AndroidFacetUtils.getResourcesRoot(AndroidFacetUtils.java:48)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.AddItemBatchScaleDialog.initController(AddItemBatchScaleDialog.java:222)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.AddItemBatchScaleDialog.<init>(AddItemBatchScaleDialog.java:147)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.AndroidBatchScaleImporter.addSingleFile(AndroidBatchScaleImporter.java:222)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.AndroidBatchScaleImporter.access$100(AndroidBatchScaleImporter.java:72)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.AndroidBatchScaleImporter$1.consume(AndroidBatchScaleImporter.java:98)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.AndroidBatchScaleImporter$1.consume(AndroidBatchScaleImporter.java:85)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:137)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:112)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:90)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.AndroidBatchScaleImporter$2.actionPerformed(AndroidBatchScaleImporter.java:135)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	
...

**Comment by MPArnold** [comment]
Confirming that this bug also applies to AS 3.6 RC 1
I don't see this as a bug in the Drawable Importer.
**getAllResourceDirectories()** is deprecated but it still can be seen [here](https://github.com/JetBrains/android/blob/master/android/src/org/jetbrains/android/facet/AndroidFacet.java).
Perhaps a later version removed it.

**Comment by MPArnold** [comment]
[Eureka](https://stackoverflow.com/questions/59871334)
