### ISSUE TITLE
Plugin install failed.  ClassNotFoundException: de.mprengemann.intellij.plugin.androidicons.IconApplication 

### ISSUE THREAD

**Issue by tuckercr** [winterDroid/android-drawable-importer-intellij-plugin#73]
There weren't any installation instructions, so after a little research I did the following:

1. Run Android Studio.
2. From the menu bar, select Android Studio > Preferences.
3. Under IDE Settings, click Plugins and then click Install plugin from disk.
4. Select the zip file (downloaded from GitHub)
5. Restart Android Studio.

But after the restart I get the following exception, and the plugin is then disabled:

Did I get the installation procedure wrong?  I am running the latest Android Studio 1.4 on OSX

```Java
Plugin 'de.mprengemann.intellij.plugin.androidicons' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.ClassNotFoundException: de.mprengemann.intellij.plugin.androidicons.IconApplication PluginClassLoader[de.mprengemann.intellij.plugin.androidicons, 0.3]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.loadClasses(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.loadClasses(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by winterDroid** [comment]
Hey! That is not the way how to install the plugin! 
Here you can find more detailed instructions: http://www.javahelps.com/2015/02/android-drawable-importer.html

**Comment by tuckercr** [comment]
Thanks.  Maybe you should put something in the GitHub readme file?

**Comment by tuckercr** [comment]
btw, sadly I couldn't use your plugin because it didn't support svg files.
