### ISSUE TITLE
NPE after updating to 0.3.1

### ISSUE THREAD

**Issue by poopaou** [winterDroid/android-drawable-importer-intellij-plugin#87]
I'm getting a NPE when i'm trying to import drawable with "Icon Pack Drawable Importer" just after 0.3.1 update on android studio 1.4.

```java
java.lang.NullPointerException
	at de.mprengemann.intellij.plugin.androidicons.controllers.icons.androidicons.AndroidIconsController.getCategories(AndroidIconsController.java:46)
	at de.mprengemann.intellij.plugin.androidicons.controllers.iconimporter.IconsImporterController.<init>(IconsImporterController.java:39)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.IconImporter.<init>(IconImporter.java:162)
	at de.mprengemann.intellij.plugin.androidicons.actions.IconsAction.actionPerformed(IconsAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by winterDroid** [comment]
Thanks for reporting the issue. Did you restart Android Studio? It seems that there are issues when parsing the bundled content.json which is weird. Which OS are you using?

**Comment by poopaou** [comment]
Yes restarting and restarting with invalidating cache doesn't fix the issue

**Comment by poopaou** [comment]
An other strange bug is when i'm using batch import, file brower windows does not work too (i'm only getting hardrives folders).

I'm on windows 7

**Comment by Nem2s** [comment]
Same strange Ex: on windows 10 with latest Android Studio.
Already tried to clear build, invalidate cache and restart android studio but can't correct it.

**Comment by winterDroid** [comment]
@poopaou / @Nem2s can you restart the IDE again, cause the exception again and afterwards attach the log (https://intellij-support.jetbrains.com/hc/en-us/articles/206827517-Locating-IDE-log-files) here either as a file or gist? if you do not want to publish it, feel free to send me an email with the log :) thanks!

**Comment by Nem2s** [comment]
this is my log: I'm on Windows 10

2015-10-15 09:56:22,505 [ 294797]  ERROR - llij.ide.plugins.PluginManager - Android Studio 1.4  Build #AI-141.2288178 
2015-10-15 09:56:22,505 [ 294797]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_51 
2015-10-15 09:56:22,505 [ 294797]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-10-15 09:56:22,505 [ 294797]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-10-15 09:56:22,505 [ 294797]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 8 
2015-10-15 09:56:22,505 [ 294797]  ERROR - llij.ide.plugins.PluginManager - Last Action: de.mprengemann.intellij.plugin.androidicons.actions.IconsAction

**Comment by winterDroid** [comment]
@Nem2s thanks for the log. But it seems there is quite a lot missing. For me the log file consists of more than 2.000 lines. Can you please check again? It should at least contain the NPE.

**Comment by Nem2s** [comment]
this is the NPE message:

null
java.lang.NullPointerException
	at de.mprengemann.intellij.plugin.androidicons.controllers.icons.androidicons.AndroidIconsController.getCategories(AndroidIconsController.java:46)
	at de.mprengemann.intellij.plugin.androidicons.controllers.iconimporter.IconsImporterController.<init>(IconsImporterController.java:39)
	at de.mprengemann.intellij.plugin.androidicons.dialogs.IconImporter.<init>(IconImporter.java:162)
	at de.mprengemann.intellij.plugin.androidicons.actions.IconsAction.actionPerformed(IconsAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by winterDroid** [comment]
Yeah I know. But before I log some information that I kind of need to fix the issue.

**Comment by poopaou** [comment]
Here is my log [file](https://gist.github.com/poopaou/dd761ace9d3a555ab700)

**Comment by winterDroid** [comment]
@poopaou Awesome thanks!

**Comment by Nem2s** [comment]
mine:

https://gist.github.com/Nem2s/f705360f9027381db6df

**Comment by sheungon** [comment]
I'm on Windows 10. Got the same issue too.

**Comment by winterDroid** [comment]
I just created a Windows VM and verified the issue. I already have a fix in
my mind and will hopefully release a hot fix today.
Am 15.10.2015 15:40 schrieb "sheungon" <notifications@github.com>:

**Comment by sheungon** [comment]
Sounds great! Thank you so much!
Your plugin is really useful! Love it! :+1: :+1:
